version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: timescaledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
